# Generated by Django 4.2 on 2023-04-20 12:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(error_messages={'max_length': 'Maximum length of 100'}, max_length=100)),
                ('question_content', ckeditor.fields.RichTextField()),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qanda.questioncategory')),
                ('reasks', models.ManyToManyField(related_name='reasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_asked'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Your answer')),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qanda.question')),
                ('who_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_answered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_answered'],
            },
        ),
    ]
