# Generated by Django 4.2 on 2023-04-19 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reasks',
            field=models.ManyToManyField(related_name='reasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
