# Generated by Django 4.1.7 on 2023-04-13 18:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Your answer')),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qanda.question')),
                ('who_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_answered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_answered'],
            },
        ),
    ]
