# Generated by Django 4.2 on 2023-04-17 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='account_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
