# Generated by Django 4.2 on 2023-04-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_individual_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stay_logged_in',
        ),
    ]
