# Generated by Django 4.2 on 2023-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('terms_of_service', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(default='M', max_length=5),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
