# Generated by Django 4.2 on 2023-04-11 07:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_termsofservice_alter_account_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofservice',
            name='terms_of_service',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
