# Generated by Django 4.2 on 2023-04-25 05:32

import articles.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_banner', models.ImageField(upload_to=articles.models.article_banner_image_upload_path)),
                ('article_title', models.CharField(error_messages={'max_length': 'Maximum length of 100'}, max_length=100)),
                ('article_content', ckeditor.fields.RichTextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='ArticleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questins', to='articles.article')),
                ('who_asked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_asked'],
            },
        ),
    ]
