# Generated by Django 4.2 on 2023-04-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlequestion_add_options_under_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlequestion',
            old_name='add_options_under_article',
            new_name='add_options_to_this_article',
        ),
    ]
