# Generated by Django 4.2 on 2023-04-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlequestion',
            name='add_options_to_this_article',
        ),
    ]
