# Generated by Django 4.2 on 2023-04-12 14:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(help_text='Write title of the course', max_length=254)),
                ('is_free', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('course_description', ckeditor.fields.RichTextField()),
                ('course_poster', models.ImageField(upload_to='course_posters', verbose_name='Course poster')),
                ('is_approved', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.ourcourse')),
                ('students', models.ManyToManyField(related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
