# Generated by Django 4.2 on 2023-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursearticle',
            name='add_options_to_this_article',
            field=models.BooleanField(default=1),
        ),
    ]
