# Generated by Django 4.2 on 2023-04-13 08:04

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcourse',
            name='course_poster',
            field=models.ImageField(upload_to=courses.models.course_poster_image_upload_path, verbose_name='Course poster'),
        ),
    ]
