# Generated by Django 4.1.7 on 2023-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_ourcourse_course_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcourse',
            name='course_title',
            field=models.CharField(max_length=254),
        ),
    ]
