# Generated by Django 4.2 on 2023-04-19 10:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursearticle',
            name='article_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursearticle',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='courses.ourcourse'),
        ),
        migrations.AddField(
            model_name='coursearticle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
