# Generated by Django 4.1.7 on 2023-04-17 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_ourcourse_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcourse',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
