# Generated by Django 4.2 on 2023-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursearticle_article_content_coursearticle_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursearticle',
            options={'ordering': ['article_identity_number']},
        ),
        migrations.AddField(
            model_name='coursearticle',
            name='article_identity_number',
            field=models.IntegerField(null=True),
        ),
    ]
