# Generated by Django 4.2 on 2023-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_ourcourse_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcourse',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ourcourse',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='EnrolledStudent',
        ),
    ]
